### ISSUE TITLE
No pause(); method on generators?

### ISSUE THREAD

**Issue by emperor-limitless** [chrisnorman7/dart_synthizer#1]
Hi

I searched the generator.dart and the context.dart and didn't find a trace of that function anywhere, Is this not implemented yet?

I didn't check, But probably since pause() Didn't exist probably play(); doesn't exist as well, So if you're planning to add pause and play was not there, It should be added as well.

Regards.

**Comment by chrisnorman7** [comment]
Hi,
Play and pause are implemented for generators, sources, and contexts. I've just added an example as part of commit 4b3827109b61650cbea1eb198688ff1bbcb514ea.
